name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  Process-PSModule:
    uses: PSModule/Process-PSModule/.github/workflows/CI.yml@split
    secrets: inherit
